# name: Run CI when action is triggered

# on:
#   push:
#   # pull_request:

# jobs:
#   link-check:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Build Docker container
#         run: docker compose build backend

#       - name: Run unit tests
#         run: docker compose run --rm backend pytest

#       - name: Start backend service
#         run: docker compose up -d backend

#       - name: Stop backend service
#         run: docker compose down
name: CI_Steps

on:
  push:

jobs:
  Linux_shell_check:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World"
  Phyton_command:
    runs-on: ubuntu latest
    steps:
      - name: Run on python
        run: python c 'print("Hello World")''
      
