Name: Run CI when action is triggerd
on: 
  - push 
  #- pull_request 
jobs:
  link-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker container
        run: docker compose build backend

      - name: Run unit tests
        run: |
          docker compose run --rm backend pytest

      - name: Start backend service
        run: docker compose up -d backend